In [55]:
import pickle
import pandas as pd

In [56]:
with open('random_forest.pkl', 'rb') as file:
    model = pickle.load(file)

In [94]:
df_2023 = pd.read_csv('data/season_2023.csv')

In [95]:
df_2023

,tp,playerId,tid,wn,mins,g,ga,oaa,pae,pw,...,blsp,blspp,currp,pss,tn,avg,slug,ip,Temporada,Jornada
0,18,1046,14,10,90,0,0,0,0,0,...,0,0,168,ok,Rayo Vallecano,18.0,dimitrievski,1,Season2023,Week10
1,18,666,2,10,76,3,0,0,0,0,...,0,0,311,ok,Atlético de Madrid,18.0,griezmann,2,Season2023,Week10
2,16,942,13,10,80,2,0,0,0,1,...,0,0,133,ok,C.A. Osasuna,16.0,budimir,3,Season2023,Week10
3,15,1452,28,10,90,0,2,2,4,0,...,0,0,173,ok,Girona FC,15.0,aleix-garcia,4,Season2023,Week10
4,14,541,4,10,90,0,1,2,0,0,...,0,0,69,ok,FC Barcelona,14.0,joao-felix,5,Season2023,Week10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7737,-1,1146,9,9,45,0,0,0,0,0,...,0,0,113,ok,Getafe CF,-1.0,alena,549,Season2023,Week9
7738,-2,360,13,9,80,0,0,0,1,0,...,0,0,62,doubtful,C.A. Osasuna,-2.0,ruben-pena,550,Season2023,Week9
7739,-2,597,10,9,90,0,0,0,0,0,...,0,0,0,ok,Granada CF,-2.0,neva,551,Season2023,Week9
7740,-2,1193,5,9,13,0,0,0,0,0,...,0,0,63,ok,Real Betis,-2.0,willian-jose,552,Season2023,Week9
7741,-2,1583,162,9,10,0,0,0,0,0,...,0,0,31,ok,Cádiz CF,-2.0,machis,553,Season2023,Week9

In [96]:
df_2023[(df_2023['pid'] != 1) & (df_2023['pid'] != 5)]

,tp,playerId,tid,wn,mins,g,ga,oaa,pae,pw,...,blsp,blspp,currp,pss,tn,avg,slug,ip,Temporada,Jornada
1,18,666,2,10,76,3,0,0,0,0,...,0,0,311,ok,Atlético de Madrid,18.0,griezmann,2,Season2023,Week10
2,16,942,13,10,80,2,0,0,0,1,...,0,0,133,ok,C.A. Osasuna,16.0,budimir,3,Season2023,Week10
3,15,1452,28,10,90,0,2,2,4,0,...,0,0,173,ok,Girona FC,15.0,aleix-garcia,4,Season2023,Week10
4,14,541,4,10,90,0,1,2,0,0,...,0,0,69,ok,FC Barcelona,14.0,joao-felix,5,Season2023,Week10
7,12,302,18,10,90,1,0,0,1,0,...,0,0,124,doubtful,Valencia CF,12.0,gaya,8,Season2023,Week10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7737,-1,1146,9,9,45,0,0,0,0,0,...,0,0,113,ok,Getafe CF,-1.0,alena,549,Season2023,Week9
7738,-2,360,13,9,80,0,0,0,1,0,...,0,0,62,doubtful,C.A. Osasuna,-2.0,ruben-pena,550,Season2023,Week9
7739,-2,597,10,9,90,0,0,0,0,0,...,0,0,0,ok,Granada CF,-2.0,neva,551,Season2023,Week9
7740,-2,1193,5,9,13,0,0,0,0,0,...,0,0,63,ok,Real Betis,-2.0,willian-jose,552,Season2023,Week9
7741,-2,1583,162,9,10,0,0,0,0,0,...,0,0,31,ok,Cádiz CF,-2.0,machis,553,Season2023,Week9

In [97]:
df_2023['Jornada'] = df_2023['Jornada'].str.split('Week').str[1].astype(int)
df_2023['Temporada'] = df_2023['Temporada'].str.split('Season').str[1].astype(int)

In [98]:
df_2023.Jornada.nunique()

14

In [99]:
df_2023.sort_values('Jornada', inplace=True, ascending=False)

In [100]:
df_2023.head()

,tp,playerId,tid,wn,mins,g,ga,oaa,pae,pw,...,blsp,blspp,currp,pss,tn,avg,slug,ip,Temporada,Jornada
2352,4,675,17,14,45,0,0,0,0,0,...,0,0,118,ok,Sevilla FC,4.0,oliver-torres,141,2023,14
2394,3,1301,28,14,85,0,0,0,1,0,...,0,0,68,doubtful,Girona FC,3.0,yangel-herrera,183,2023,14
2400,3,1183,31,14,24,0,0,0,2,0,...,0,0,0,ok,UD Las Palmas,3.0,sandro,189,2023,14
2399,3,1032,14,14,90,0,0,0,0,0,...,0,0,223,ok,Rayo Vallecano,3.0,isi,188,2023,14
2398,3,567,17,14,89,0,0,0,1,0,...,0,0,67,ok,Sevilla FC,3.0,ocampos,187,2023,14

In [101]:
df_2023 = df_2023[['mins','tp','pm','g','ga','oaa','pae','wc','tsa','br','pla','rc','yc','syc','pf','pc','m','slug','Temporada','Jornada']]

In [102]:
for column in df_2023.columns:
    if column not in ['Temporada','slug','Jornada'] and column in df_2023.columns:
        df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
        df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))

C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_mean_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).mean().shift(1))
C:\Users\Alejandro\AppData\Local\Temp\ipykernel_24068\3123820869.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023.loc[:, f'{column}_std_last_3'] = df_2023[column].transform(lambda x: x.rolling(window=3).std().shift(1))

In [103]:
df_2023['index'] = delanteros.slug
df_2023 = delanteros.set_index('index')
df_2023.drop(columns=['slug'], inplace=True)

NameError: name 'delanteros' is not defined

In [104]:
df_2023 = df_2023.fillna(0)

In [86]:
gw_14 = df_2023[df_2023['Jornada']==14]
df_2023 = df_2023[df_2023['Jornada'] !=14]

In [87]:
gw_14_predict = gw_14.copy()

In [88]:
suffixes_to_exclude = ['_last_3', 'Temporada', 'Jornada']
columns_to_reset = [col for col in gw_14_predict.columns if not any(suffix in col for suffix in suffixes_to_exclude)]
gw_14_predict[columns_to_reset] = 0
gw_14_predict.head()

,mins,tp,pm,g,ga,oaa,pae,wc,tsa,br,...,yc_mean_last_3,yc_std_last_3,syc_mean_last_3,syc_std_last_3,pf_mean_last_3,pf_std_last_3,pc_mean_last_3,pc_std_last_3,m_mean_last_3,m_std_last_3
2352,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2394,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2400,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2399,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2398,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [89]:
gw_14_predict = gw_14_predict.fillna(0)

In [90]:
gw_14

,mins,tp,pm,g,ga,oaa,pae,wc,tsa,br,...,yc_mean_last_3,yc_std_last_3,syc_mean_last_3,syc_std_last_3,pf_mean_last_3,pf_std_last_3,pc_mean_last_3,pc_std_last_3,m_mean_last_3,m_std_last_3
2352,45,4,2,0,0,0,0,1,0,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000
2394,85,3,1,0,0,0,1,1,0,6,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000
2400,24,3,1,0,0,0,2,0,1,1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.00000
2399,90,3,2,0,0,0,0,0,1,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.00000
2398,89,3,2,0,0,0,1,0,0,9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2582,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.333333,0.57735
2580,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.333333,0.57735
2579,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.666667,0.57735
2578,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.00000
2581,0,0,0,0,0,0,0,0,0,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.00000

In [93]:
import numpy as np
X_pred = gw_14_predict.drop(['tp','mins'], axis=1)  # Features
y_real = gw_14['tp']
# Calcular las predicciones
predicciones = model.predict(X_pred[['tp_mean_last_3',
  'g',
  'tp_std_last_3',
  'ga',
  'oaa',
  'Jornada',
  'pla',
  'br',
  'pla_std_last_3',
  'mins_std_last_3']])

# Calcular el error
error = np.mean((y_real - predicciones)**2)

# Imprimir el error
print("Error:", error)

Error: 0.9713544303797468

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Assuming 'points' is the column with the points and 'player' is the column with the player names
top_5_players = df.sort_values('points', ascending=False).head(5)

plt.figure(figsize=(10, 6))
sns.barplot(x='player', y='points', data=top_5_players)
plt.title('Top 5 Players with Most Points')
plt.xlabel('Player')
plt.ylabel('Points')

# Save the plot as an HTML file
plt.savefig('barplot.html')